---
- hosts: all
  become: false
  gather_facts: true

  tasks:

    - name: Get the current caller identity information
      amazon.aws.aws_caller_info:
      register: caller_info

    - name: Create IAM Role and Profile
      ansible.builtin.import_tasks: "tasks/create_iam.yml"

    - name: Create S3 Bucket
      ansible.builtin.import_tasks: "tasks/create_bucket.yml"

    - name: Find RHEL AMI
      ansible.builtin.import_tasks: "tasks/get_rhel_ami.yml"

    - name: Create Component and Recipe
      ansible.builtin.import_tasks: "tasks/create_component.yml"

    - name: Create Distribution
      ansible.builtin.import_tasks: "tasks/create_distribution.yml"

    - name: Create Infrastructure
      ansible.builtin.import_tasks: "tasks/create_infrastructure.yml"

    - name: Create Pipeline
      ansible.builtin.import_tasks: "tasks/create_pipeline.yml"
