---

  - name: Upload component config in S3 bucket
    amazon.aws.aws_s3:
      bucket: "{{ bucket_name }}"
      object: "component_config.yaml"
      content: "{{ lookup('template', 'templates/component_config.yaml.j2') }}"
      mode: put

  - name: Cleanup temp files
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    loop:
      - "/tmp/image_component_config.json"
      - "/tmp/image_recipe_config.json"

  - name: Template Image Component Config
    ansible.builtin.template:
      src: image_component_config.json.j2
      dest: /tmp/image_component_config.json

  - name: Create the custom component
    shell: |
      aws imagebuilder create-component --cli-input-json file:///tmp/image_component_config.json

  # It takes time for the list to update. Wait
  - name: Pause for 15 seconds to build app cache
    ansible.builtin.pause:
      seconds: 15

  - name: List component build version
    shell: |
      aws imagebuilder list-components --owner Self --query 'componentVersionList[].arn' --output text
    register: component_info

  - name: Show component version ARN
    debug:
      var: component_info

  - name: Set component_version_arn fact
    set_fact:
      component_version_arn: "{{ component_info.stdout }}"

  - name: Get Component Build Version Arn
    shell: |
      aws imagebuilder list-component-build-versions --component-version-arn "{{ component_version_arn }}" --query 'componentSummaryList[].arn' --output text
    register: component_build_info

  - name: Show component build version ARN
    debug:
      var: component_build_info

  - name: Set component_build_version_arn fact
    set_fact:
      component_build_version_arn: "{{ component_build_info.stdout }}"

  - name: Template Image Recipe Config
    ansible.builtin.template:
      src: image_recipe_config.json.j2
      dest: /tmp/image_recipe_config.json

  - name: Create a custom image recipe
    shell: |
      aws imagebuilder create-image-recipe --cli-input-json file:///tmp/image_recipe_config.json

  # It takes time for the list to update. Wait
  - name: Pause for 15 seconds for image recipe create
    ansible.builtin.pause:
      seconds: 15

  - name: List image recipe
    shell: |
      aws imagebuilder list-image-recipes --query "imageRecipeSummaryList[].arn" --output text
    register: image_recipe_info

  - name: Set image_recipe_arn fact
    set_fact:
      image_recipe_arn: "{{ image_recipe_info.stdout }}"
