#!/bin/bash

  - name: Cleanup temp files
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    loop:
      - "/tmp/image_infra_config.json"

  - name: Template Image Infra Config
    ansible.builtin.template:
      src: image_infra_config.json.j2
      dest: /tmp/image_infra_config.json

  - name: Create infrastructure configuration
    shell: |
      aws imagebuilder create-infrastructure-configuration --cli-input-json file:///tmp/image_infra_config.json

  # It takes time for the list to update. Wait
  - name: Pause for 15 seconds to build app cache
    ansible.builtin.pause:
      seconds: 15
 
### List all infrastructure configurations
#aws imagebuilder list-infrastructure-configurations
 
  - name: Get details on Infrastructure configuration
    shell: |
      aws imagebuilder list-infrastructure-configurations --query 'infrastructureConfigurationSummaryList[].arn' --output text
    register: infra_config_info

  - debug:
      var: infra_config_info

  - name: Set infra_config_arn fact
    ansible.builtin.set_fact:
      infra_config_arn: "{{ infra_config_info.stdout }}"

#aws imagebuilder get-infrastructure-configuration --infrastructure-configuration-arn $INFRA_CONF_ARN
